name: Self-Hosted CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Ajout d'un déclencheur manuel pour faciliter les tests
  workflow_dispatch:

jobs:
  build-and-test:
    # Spécifie d'utiliser votre runner auto-hébergé au lieu des runners GitHub
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log Node.js version
      run: node --version

    - name: Log available disk space
      run: |
        echo "Checking available disk space:"
        df -h

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless --no-progress
